---
# tasks related to tools for role-laptop-opensuse
- name: refresh the cache
  zypper:
    name: "{{ zypper_tool }}"
    state: present
  update_cache: yes
  force: yes
  with_items:
    - htop
    - tmux
    - sysstat
    - PlayOnLinux
    - MozillaFirefox
    - chromium
    - trickle
    - IPython
    - python-virtualenvwrapper
  loop_control:
    loop_var: zypper_tool
